### ISSUE TITLE
Error: Cannot read property 'owner' of undefined

### ISSUE THREAD

**Issue by tymokvo** [TreTuna/sync-branches#45]
Hello,

I am trying to use this workflow to open a PR from master to a test branch, but it is failing with `Error: Cannot read property 'owner' of undefined`. I think this is coming from [this line](https://github.com/TreTuna/sync-branches/blob/64764390782c8f81301da5b54aaf4daef4889de1/dist/index.js#L2002) but I am not sure why the repository would be `undefined`.

The workflow file is:
```yaml
name: Update test branches

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  upate-master-test:
    runs-on: ubuntu-latest
    name: Update test branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Open pull request
        id: pull-request
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "test"
          PULL_REQUEST_TITLE: "Update: {FROM_BRANCH} -> {TO_BRANCH}"
          PULL_REQUEST_BODY: "Update: {FROM_BRANCH} -> {TO_BRANCH}"
```

Thanks for any help!
