### ISSUE TITLE
Problems creating two PR's

### ISSUE THREAD

**Issue by SamuelMolling** [TreTuna/sync-branches#70]
Basically I'm using this action to create a PR by syncing a development branch for staging and after merging in staging, open the PR from staging to master. But this second PR is never triggered and I don't understand why. Follow my workflow.

They are two different files.

dev2stg.yml

```
name: Create PR Automatic to Staging
on:
  push:
    branches:
      - develop
    paths:
      - PATH
      - .github/**
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          FROM_BRANCH: 'develop'
          TO_BRANCH: 'staging'
```

stg2prd.yml

```
name: Create PR Automatic to Master
on:
  push:
    branches:
      - staging
    paths:
      - PATH
      - .github/**
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-bran
![Screenshot 2023-01-07 at 09 47 12](https://user-images.githubusercontent.com/56612163/211151341-55adc2f7-52eb-45a3-b47c-41b223fd342b.png)
ches@1.4.0
        with:
          FROM_BRANCH: 'staging'
          TO_BRANCH: 'master'
```

From the image you can see that everything ran correctly and the merge was done, but the workflow was not triggered
