### ISSUE TITLE
Error: Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}

### ISSUE THREAD

**Issue by NullVoxPopuli** [TreTuna/sync-branches#75]
This is from a workflow triggered by cron:
https://github.com/NullVoxPopuli/limber/actions/runs/4533764809/jobs/7987019509#step:5:22

Whole workflow is here:
```yml
name: Preview Embroider Upgrade
on:
  schedule:
    # Runs "at minute 0 minutes past midnight" (see https://crontab.guru)
    # - cron: '0 0 * * *'
    - cron: '0/30 * * * *'

env:
  branch: "use-unstable-embroider"
  title: "[Unstable] Preview embroider upgrade"
  body: |
    Automated and continuously updated PR (nightly via cron)
    _Do not merge_

jobs:
  update_unstable_branch:
    name: Update Unstable Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: ./dev/update-unstable-embroider.sh
      - uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_BRANCH: ${{ env.branch }}
          TO_BRANCH: 'main'
          PULL_REQUEST_TITLE: ${{ env.title }}
          PULL_REQUEST_BODY: ${{ env.body }}
```
